{
 "title": "Bluesky",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "did", "label": "DID" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  { "title": "Bluesky Firehose", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Firehose Ops ($interval avg) ${did} ${filter}",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate({job=\"bluesky-firehose\"} | json collection, action | collection != `` | action != `no_ops` |~ `\"repo\":\"${did}` |= `${filter}` [$interval])",
     "legendFormat": "{{collection}} ({{action}})"
    }
   ]
  },
  {
   "title": "Throughput (ops/s)",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Throughput (ops/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Throughput (ops/s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Recent $collection",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{job=\"bluesky-firehose\"} | json collection, action, repo | action != `no_ops` |~ `\"repo\":\"${did}` |= `${filter}`"
    }
   ]
  },
  {
   "title": "Handle Changes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"bluesky-firehose\"} | json handle=\"meta.handle\" | handle!=\"\""
    }
   ]
  },
  { "title": "Firehose Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } }
 ]
}